repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.5.0
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.1
    hooks:
      - id: check-jsonschema
        name: "Match meta.ymls in one of the subdirectories of modules/ph-core"
        files: ^modules/ph-core/.*/meta\.yml$
        types: [yaml]
        args: ["--schemafile", "modules/yaml-schema.json"]
      - id: check-jsonschema
        name: "Validate environment.ymls against schema"
        files: ^modules/ph-core/.*/environment\.yml$
        types: [yaml]
        args: ["--schemafile", "modules/environment-schema.json"]
      - id: check-jsonschema
        name: "Match meta.ymls in one of the subdirectories of subworkflows/ph-core"
        files: ^subworkflows/ph-core/.*/meta\.yml$
        types: [yaml]
        args: ["--schemafile", "subworkflows/yaml-schema.json"]
      - id: check-github-workflows
  # use ruff for python files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        files: \.py$
        args: [--fix, --exit-non-zero-on-fix, "--select", "I,E1,E4,E7,E9,F,UP,N"] # sort imports and fix (rules taken from ph-core/tools)
      - id: ruff-format # formatter
