name: Run nf-test
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/meta.yml"
      - "**/*.md"
      - "**/*.png"
      - "**/*.svg"
  release:
    types: [published]
  workflow_dispatch:

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NFT_VER: "0.9.5"
  NF_CORE_VER: "3.5.1"
  NFT_WORKDIR: "/home/runner"
  NXF_ANSI_LOG: false

jobs:
  nf-test-changes:
    name: nf-test-changes
    runs-on: ubuntu-latest
    outputs:
      shard: ${{ steps.set-shards.outputs.shard }}
      total_shards: ${{ steps.set-shards.outputs.total_shards }}
    steps:
      - name: Clean Workspace
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: get number of shards
        id: set-shards
        uses: ./.github/actions/get-shards
        env:
          NFT_VER: ${{ env.NFT_VER }}
        with:
          max_shards: 7

  nf-test:
    name: "docker | ${{ matrix.NXF_VER }} | ${{ matrix.shard }}/${{ needs.nf-test-changes.outputs.total_shards }}"
    needs: [nf-test-changes]
    if: ${{ needs.nf-test-changes.outputs.total_shards != '0' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: ${{ fromJson(needs.nf-test-changes.outputs.shard) }}
        profile: [docker]
        NXF_VER:
          - "24.10.5"
          - "latest-everything"
    env:
      NXF_ANSI_LOG: false
      TOTAL_SHARDS: ${{ needs.nf-test-changes.outputs.total_shards }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Run nf-test
        id: run_nf_test
        uses: ./.github/actions/nf-test
        continue-on-error: ${{ matrix.NXF_VER == 'latest-everything' }}
        env:
          NXF_VERSION: ${{ matrix.NXF_VER }}
          NFT_WORKDIR: ${{ env.NFT_WORKDIR }}
        with:
          profile: ${{ matrix.profile }}
          shard: ${{ matrix.shard }}
          total_shards: ${{ env.TOTAL_SHARDS }}

      - name: Report test status
        if: ${{ always() }}
        run: |
          if [[ "${{ steps.run_nf_test.outcome }}" == "failure" ]]; then
            echo "::error::Test with ${{ matrix.NXF_VER }} failed"
            echo "## Test failed: docker | ${{ matrix.NXF_VER }} | Shard ${{ matrix.shard }}/${{ env.TOTAL_SHARDS }}" >> $GITHUB_STEP_SUMMARY
            if [[ "${{ matrix.NXF_VER }}" == "latest-everything" ]]; then
              echo "::warning::Test with latest-everything failed but will not cause workflow failure."
            fi
            if [[ "${{ matrix.NXF_VER }}" != "latest-everything" ]]; then
              exit 1
            fi
          fi

  confirm-pass:
    needs: [nf-test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: One or more tests failed (excluding latest-everything)
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: One or more tests cancelled
        if: ${{ contains(needs.*.result, 'cancelled') }}
        run: exit 1

      - name: All tests ok
        if: ${{ contains(needs.*.result, 'success') }}
        run: exit 0
